export default function Ex06() {
    return (
      <p className="overflow-scroll w-[500px] h-[200px]">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit modi perspiciatis cum natus corrupti iste consequuntur error tempore! Labore reprehenderit nostrum consectetur sit aut debitis totam vel explicabo pariatur dolores!
        Velit repellat tenetur architecto deleniti maxime, aut omnis sed quis tempora pariatur minus reiciendis cum odio ex, quos magnam a, voluptatibus ipsum sequi commodi. Ratione esse est ducimus consequatur totam.
        Quis, totam veniam exercitationem nostrum numquam cum enim sequi quam doloribus, eveniet ullam tenetur magni earum eaque iste ratione maxime error? Autem repellendus atque quas voluptatibus quo doloremque sed a.
        Cum, provident amet soluta voluptatum assumenda voluptatem facilis eum praesentium incidunt quis impedit perspiciatis magni suscipit, vero earum vel cumque laboriosam in nemo. Illum fugit odit illo ratione quam blanditiis.
        Soluta sequi expedita quidem, labore earum repellat inventore adipisci cupiditate doloribus ab corrupti unde culpa, doloremque distinctio nemo sit! Vero soluta hic quod eius deserunt aperiam mollitia ratione natus maxime.
        Expedita, distinctio reprehenderit ab, vel, illo harum veniam maiores maxime voluptatem ullam in! Repellendus ut laborum provident dolor commodi, fuga hic pariatur voluptates dolores sed iste velit obcaecati officiis molestiae.
        Excepturi error labore voluptatibus minima eveniet cum, consequatur rerum facilis, reiciendis, doloremque quaerat quasi aliquid ut libero pariatur. Accusamus ipsum, veniam natus itaque consectetur laudantium necessitatibus id pariatur tempora ullam?
        Dolore sapiente culpa, a aut tempora voluptate quo at harum perferendis quam cupiditate hic dolorem odio, sint tenetur qui earum amet asperiores natus, dolorum maiores quis! Minima iusto magnam expedita.
        Dicta mollitia hic sint ratione, qui esse atque molestias dolores error nobis pariatur eaque voluptate iure deserunt enim nisi, delectus, fuga ipsa? Laudantium blanditiis, corrupti dolor suscipit ad totam nemo?
        Adipisci ad numquam maxime totam cupiditate id et recusandae earum, laudantium illum quasi fugiat modi possimus voluptatum odio inventore dolore, iste maiores! Neque, totam! Laborum repellat beatae explicabo saepe eligendi.
        Amet blanditiis repellendus distinctio quibusdam? Iusto ipsa iure doloremque cumque vitae veritatis doloribus voluptate error repellat dolore pariatur quam exercitationem illo labore quaerat consequuntur neque eos fugit quibusdam, eveniet veniam.
        Sed facere ullam autem porro soluta, deserunt ut ducimus doloremque, facilis nihil perspiciatis. Ipsam non quod id ipsum odit illo omnis soluta, distinctio, autem asperiores ea veritatis aspernatur aut rerum.
        Deserunt, praesentium unde dolor ipsam nesciunt magni. Fugit suscipit fugiat doloremque, dignissimos ullam eos, quisquam molestias dolor temporibus ipsa, eligendi est magnam quis voluptas. Quos officiis nihil a sapiente doloribus!
        A, debitis unde incidunt iusto quisquam nesciunt libero animi deserunt consequuntur sit? Numquam modi expedita nobis nesciunt? Sequi architecto nihil ducimus quisquam fuga, eius iste natus nostrum similique provident perferendis!
        Saepe eaque porro quia officiis possimus provident ipsa itaque in tenetur ullam pariatur maxime, voluptatibus, et aspernatur dignissimos architecto ea necessitatibus cumque doloremque! Vero id facere nisi, repellat impedit delectus.
        Facilis laudantium magnam, molestias cumque nisi nam consequuntur enim velit quos expedita alias. Ipsam labore, reiciendis ratione esse veniam in! Incidunt provident quidem iste odio modi saepe suscipit doloremque aut.
        Ex facilis cum eos neque blanditiis iste libero necessitatibus. Illum delectus fugiat repudiandae, labore optio voluptate vel velit adipisci minus quas facere ipsum amet omnis similique, aspernatur culpa eos. Vel.
        Asperiores nemo recusandae excepturi nesciunt, fugit aut dicta temporibus omnis? Architecto hic sed, cupiditate voluptatibus numquam quasi quae fuga quidem? Alias deserunt consectetur mollitia doloribus rerum ab distinctio aliquam enim.
        Nobis soluta non velit doloribus at aut aliquid aperiam a quos? Natus sunt optio vel error, sapiente, quisquam esse autem ratione commodi asperiores laborum nobis provident sequi inventore architecto velit.
        Debitis vel eius error odio dolores placeat ipsam voluptate, sint commodi aperiam ut, ipsum sit deserunt nulla incidunt quasi voluptatem similique sunt sequi quia aspernatur sed perspiciatis? Doloribus, commodi ex?
        Praesentium iusto tempore voluptate aliquam quasi ex ad. Corporis velit harum porro nemo sapiente rem molestias explicabo sint aut similique ullam, eveniet culpa voluptatibus modi sunt dolor dolores distinctio facilis!
        Dolor explicabo deleniti sapiente doloribus similique. Tempore ad cupiditate sapiente adipisci libero ullam, tenetur suscipit! Iure quia necessitatibus aliquid, repudiandae asperiores tempore minima voluptatibus dolorem dolores ullam temporibus neque reprehenderit?
        Qui cupiditate illo quos ducimus magnam hic rerum, nihil laboriosam placeat molestiae nulla quisquam laudantium suscipit a officia, deserunt nostrum? Praesentium fugit iure ab, ullam reiciendis voluptatem omnis doloremque itaque!
        Aliquid, voluptas officiis laboriosam dolores provident dolorum voluptatum ex nostrum numquam consectetur non voluptates, aspernatur animi? Quibusdam fugit possimus magnam. Dolorem reprehenderit libero voluptas rem velit iure dolore corrupti dicta!
        Facere quia, doloribus provident, consequatur, mollitia quaerat delectus excepturi veritatis quae laudantium necessitatibus beatae tempore! Natus fugiat dicta quo rerum magnam, suscipit reiciendis dolorem voluptatibus consectetur, quibusdam dolor dignissimos ipsam.
        Adipisci, fugit cupiditate? Dolore, at cumque accusamus ullam labore itaque ipsum quae in repellat ea! Possimus eveniet deleniti, fugiat, laboriosam odit cumque numquam, ipsa dolor necessitatibus porro in velit molestiae!
        Placeat dolore suscipit tempore, laboriosam maxime dolorem numquam ducimus inventore animi reiciendis, eos unde! Cupiditate quibusdam nihil maiores magni nemo et consequatur iure ullam, iste, facere fuga, ad quos saepe!
        Dicta tempora voluptatum fugit, reiciendis itaque minus odio modi unde voluptatibus sed maxime commodi molestias possimus natus, nobis nihil, sit rem delectus cumque. Illo placeat aliquam repellendus vitae laudantium cum.
        Dolorum quo ipsam, provident laborum facere molestiae blanditiis et vero? Culpa tempora saepe repellat ipsum nostrum et vel quod qui! Quae perferendis voluptatibus consequuntur beatae ad. Repellat voluptatem impedit nobis!
        Itaque minima temporibus error aperiam asperiores reiciendis quaerat blanditiis? Distinctio tempore ad esse labore nihil ratione culpa rem asperiores cumque dolorem pariatur, provident eum delectus excepturi nam molestias corrupti recusandae?
        Totam consequatur reiciendis non earum, et, harum iure eligendi assumenda animi exercitationem, eos facilis recusandae quidem! Laboriosam veritatis quia quibusdam, ullam aliquam ab maxime rerum vero perferendis distinctio, dolorum suscipit?
        Enim dignissimos ipsa, perspiciatis rem eos quas consequuntur mollitia aspernatur, atque eius, tempore aperiam qui in cupiditate. Aliquid ea accusantium sint culpa dolores deleniti modi, harum amet iusto ipsam minus.
        Maiores, praesentium quibusdam quia aliquid ipsam adipisci id recusandae dolorum ut repellat et ratione incidunt quas? Et, deserunt amet officiis quae itaque quia explicabo aliquam voluptatem dignissimos saepe assumenda. Deserunt!
        Impedit minus et aliquam suscipit, optio in pariatur, modi facilis eos amet, incidunt animi vero quis sed inventore ab? Quisquam perferendis quasi suscipit animi sit soluta temporibus dolorum quia eius!
        Nisi excepturi quaerat, dolorem enim pariatur unde, voluptas blanditiis aliquam molestiae ullam dolor id qui fuga ipsum iure non voluptatum laudantium a magnam itaque. Dolore incidunt illum labore aliquam est!
        Adipisci ut eum, sequi ea minima officiis odit consectetur earum provident est molestiae ipsam veritatis expedita facere totam deleniti quibusdam quos sunt dolor dolores magni harum ratione? Est, praesentium eaque.
        Quod aspernatur veniam architecto distinctio unde quam, doloremque voluptatibus veritatis praesentium adipisci delectus reiciendis, repudiandae quis neque quidem harum soluta iure? Esse, velit ex? Eaque ab minus excepturi minima impedit?
        Inventore fugit adipisci accusantium illo illum nihil earum consectetur aperiam magni debitis! Inventore ipsa, blanditiis, nemo deleniti magni mollitia rerum quod, error facilis ab voluptatibus beatae sed et accusantium dolorem?
        Nemo rerum culpa consequatur expedita neque officiis ipsa enim perspiciatis itaque aspernatur nobis labore repellat, ipsam modi laborum tempora consequuntur ab quos! Quo minima sequi est! Dignissimos nihil expedita laborum!
        Totam architecto culpa aliquid exercitationem saepe? Odio temporibus odit accusamus tenetur dolore consectetur molestiae, itaque eum eius illo numquam nobis molestias, sapiente veniam nihil modi architecto esse omnis corrupti amet?
        Quidem possimus aliquid maxime facere vero eaque accusamus ad sit? Maxime ut animi optio error minus est quod, perspiciatis assumenda vel itaque tenetur. Numquam, iusto! Rem suscipit reprehenderit totam nam!
        Sed hic eligendi rerum at laboriosam eaque doloremque tempore dolor iusto? Magnam ut nihil, optio deserunt ab rem doloribus dicta cum maiores voluptatem sit harum veritatis expedita, nostrum labore vero?
        Facilis debitis eos veritatis exercitationem deserunt cum eveniet necessitatibus aut et laboriosam soluta expedita ipsum sed amet nostrum perferendis aliquam facere quidem, ducimus quis, distinctio provident nam? Minima, maxime cumque.
        Quia fugiat eaque vel aut laborum asperiores sint ab ipsum officiis. Perferendis voluptate nobis similique fuga aliquam accusamus ea corrupti mollitia ullam quaerat eos beatae, dolor recusandae iusto dolore a.
        Reprehenderit dicta quisquam culpa eum a quae rem ratione obcaecati non, architecto sit nisi ad cupiditate earum, at maxime nesciunt beatae sapiente esse veniam accusamus. Numquam nisi eligendi aspernatur nobis?
        Cum nam architecto, natus laborum minus reprehenderit quisquam laudantium. Et praesentium, itaque nam doloremque odit dicta minima esse iste molestias aperiam voluptatum amet, sequi enim incidunt laudantium obcaecati iusto culpa.
        Praesentium cumque placeat debitis incidunt nisi sequi, quas, asperiores velit ex aspernatur recusandae dolores autem explicabo dicta mollitia! Ipsam voluptas cum totam ad commodi blanditiis iure expedita dignissimos inventore mollitia.
        Accusantium illo explicabo reprehenderit officia possimus obcaecati provident in, assumenda, impedit tenetur beatae ab ipsa numquam blanditiis expedita voluptas maxime est, mollitia quo odio. Provident deleniti perferendis sapiente culpa eum.
        Voluptatibus itaque iste, veritatis eveniet nam obcaecati libero esse corrupti possimus nesciunt laborum consequuntur molestias ducimus deserunt perspiciatis consequatur earum assumenda animi pariatur quod! Animi sapiente blanditiis nesciunt ducimus distinctio.
        Dicta odit eligendi exercitationem, dolorum laborum harum, commodi fuga facere assumenda incidunt excepturi perferendis minima dignissimos at quibusdam dolores cum? Odit eligendi quos nam excepturi tempora exercitationem quae libero molestias.
      </p>
    )
  }